### ISSUE TITLE
Same object reference is used for every item in array

### ISSUE THREAD

**Issue by Lange** [chute/json-schema-defaults#10]
Hi there!

I have the following schema snippet:
```json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",

	"properties": {
		"osc": {
			"type": "object",
			"properties": {
				"address": {
					"type": "string",
					"description": "The IP address or hostname of a Behringer X32 digital mixer."
				},
				"gameAudioChannels": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"sd": {
								"type": ["integer", "null"]
							},
							"hd": {
								"type": ["integer", "null"]
							}
						}
					},
					"minItems": 4,
					"maxItems": 4
				}
			},
			"required": ["address", "gameAudioChannels"]
		}
	}
}
``` 

(It's used to define some config parameters used to monitor the fader and mute status of certain audio channels on the Behringer X32 digital mixer, via its OSC protocol)

My expectation is that the resulting `osc.gameAudioChannels` would be an array of four unique empty objects. However, due to [defaults.js#L194](https://github.com/chute/json-schema-defaults/blob/master/lib/defaults.js#L194), **the same object reference is pushed to every index of the array**. This means that later on in my application when I try to mutate these objects, any mutation made to one index affects all indices.

I think that changing default.js#L194 to the following would be sufficient to resolve the problem:
```js
values.push(cloneJSON(value));
```

Thanks for your time and for this very useful library!
Alex

**Comment by petrbela** [comment]
Thanks for this suggestion, released as 0.3.0
