### ISSUE TITLE
Can this be used to add missing defaults to an existing structure?

### ISSUE THREAD

**Issue by dtgriscom** [chute/json-schema-defaults#12]
My current product reads configuration from a JSON file, validated by a JSON schema. From time to time I add new values to the configuration, and thus add new specs to the schema. Problem: this invalidates any saved configurations.

I'd like to use json-schema-defaults to automatically add default values to any missing values. In other words, I'd hand a configuration structure and a schema with defaults to json-schema-defaults, and get a returned structure that has newly-added defaults so that it can validate against the schema.

I've looked through the doc and tests, but couldn't find anything that suggested how I could do this. Can json-schema-defaults be used to do this? If not, would you consider this a feature request?

Thanks,
Dan

**Comment by petrbela** [comment]
This sounds like #9. Would that work for you?

**Comment by dtgriscom** [comment]
That's a good solution for someone who's already using lodash, but I'd rather not add that whole (large) package for this one need. You called that request "out of scope"; do you still feel that way? (I'm happy to try persuading you otherwise...)

**Comment by petrbela** [comment]
The thing is, I'd be duplicating code that's already written and tested in another (widely-used) library. If you're concerned about the size, you can import just that single function:

```js
import defaultsDeep from 'lodash/defaultsDeep'
```

Or, this function is even available as a separate module: https://www.npmjs.com/package/lodash.defaultsdeep

Unless there's a use-case that `defaultsDeep` doesn't cover, I'd rather keep this module as small (and simple) as possible.

**Comment by dtgriscom** [comment]
Well, darn. It's hard to argue against a well-focused mandate.


Thanks,
Dan

**Comment by petrbela** [comment]
:)

**Comment by dtgriscom** [comment]
Well, I'm back. I've looked at lodash's defaultsDeep, and it actually isn't a good solution for my needs. I'd guessed that it would use the `default` property of JSON schemas, but it doesn't understand schemas. Instead, I have to have two specification structures: one with the JSON schema validating the data, and a separate one with default values to be added. Schemas are already fairly complex; to have to maintain a separate, complex structure with all the defaults invites errors.

I'm currently using `jsonschema` for validation, but it doesn't handle the `default` property of the schema. I'd like to use `json-schema-defaults` for defaults, but it doesn't handle adding default values to pre-existing values. So, I find myself in a functionality gap. I suspect there are a lot of people in the same bind (anyone who has to update an existing JSON file to a new spec, adding defaults).

Is this a hard thing to add to your system? Would it break existing uses?

**Comment by petrbela** [comment]
`defaultsDeep` doesn't understand JSON schema `default`s, `json-schema-defaults` does. To achieve what you need, you need to combine the two:

```js
import defaultsDeep from 'lodash/defaultsDeep'
import jsonSchemaDefaults from 'json-schema-defaults'

const mySchema = ...
const myExistingObject = ...

const result = defaultsDeep(myExistingObject, jsonSchemaDefaults(mySchema))
```

If this doesn't work for you, can you please post an example of the data you have?
