### ISSUE TITLE
Support resolving $refs that point to other local files on disk

### ISSUE THREAD

**Issue by Lange** [chute/json-schema-defaults#13]
Hello!

I have a big project that uses many, many JSON schemas split up in dozens of files. I have one folder called `types` which contains schemas that many other schemas reference via `$ref` statements.

I'd like to add support to `json-schema-defaults` for resolving these file `$ref`s. I can see two routes that would both need to be supported:

1. If a filepath is provided as the first argument, automatically take care of parsing that file and resolving any `$ref`s relative to that filepath.
2. If a JSON object is provided as the first argument, the caller would need to also supply some option that tells `json-schema-defaults` what directory to start in when resolving file `$ref`s.

Does this sound like functionality that you want in this package? If so, I'll work on a pull request.

Thanks!
Alex

**Comment by Lange** [comment]
Oops, I spoke too soon.

Turns out that the incredible [json-schema-ref-parser](https://github.com/BigstickCarpet/json-schema-ref-parser) is purpose-built for this exact task, and its output can be fed directly into `json-schema-defaults`. Maybe adding a link to the README would be helpful?

**Comment by petrbela** [comment]
Great that you were able to get it working. Using a separate package is indeed the preferred way to do it.
